version: '3.8'

services:
  aubon-backend:
    build:
      target: dev
    volumes:
      - ./backend:/backend
    container_name: aubon-backend
    image: aubon-backend:1.0.0
    ports:
      - '3000:3000'