version: '3.8'

volumes:
  db_data:

networks:
  backend:

services:
  aubon-db:
    image: postgres:14.2-alpine3.15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER-aubon}
      - POSTGRES_PASSWORD=${DB_PASSWORD-aubon}
      - POSTGRES_DB=aubon
      - POSTGRES_INITDB_ARGS=--lc-collate='sv_SE.UTF-8'
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - backend
  aubon-backend:
    build:
      context: backend
    depends_on:
      - 'aubon-db'
    expose:
      - '3000'
    networks:
      - backend
    environment:
      - DB_USER=${DB_USER-aubon}
      - DB_PASSWORD=${DB_PASSWORD-aubon}
