name: Deploy

on:
  push:
    branches: ["feat/production-docker"]

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create deployment artifact
        run: tar -czf "${{ github.sha }}".tar.gz --exclude=.git* --exclude=app * .??*
      - name: Start docker container
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          source: ${{ github.sha }}.tar.gz
          target: /var/www/aubon/
      - name: Start docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/aubon
            tar xzf "${{ github.sha }}".tar.gz
            rm "${{ github.sha }}".tar.gz
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
