name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create deployment artifact
        run: tar -czf "${{ github.sha }}".tar.gz --exclude=.git* --exclude=app * .??*
      - name: Start docker container
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          source: ${{ github.sha }}.tar.gz
          target: /var/www/aubon/releases/${{ github.sha }}
      - name: Start docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/aubon/releases/${{ github.sha }}
            tar xzf "${{ github.sha }}".tar.gz
            rm "${{ github.sha }}".tar.gz
            cd /var/www/aubon
            ln -sfn releases/${{ github.sha }} current
            cd current
            docker-compose -p aubon -f docker-compose.yml -f docker-compose.prod.yml up -d --build
            docker exec aubon-backend-prod db-migrate up -e prod
