name: Deploy

on:
  push:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          script: ls

# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build